Voter reg form scholarship modal
DoSomething/phoenix-next pull request #2355
Opened 2020-09-10 20:11 UTC by lindsayrmaher

### What's this PR do?

This pull request adds a new modal option to the campaign banner. This is intended to be the initial modal users see before they take the quiz, but the regular scholarship details modal should display if they've dismissed. (that work will come in a follow up PR). 

### How should this be reviewed?

Does this implementation make sense? Is the naming reasonable? 

**Screenshots:**
![Screen Shot 2020-09-10 at 4 09 59 PM](https://user-images.githubusercontent.com/15236023/92797475-1c09f700-f380-11ea-8e5e-82517c313138.png)

![Screen Shot 2020-09-10 at 4 09 44 PM](https://user-images.githubusercontent.com/15236023/92797495-1f9d7e00-f380-11ea-98cc-3b8e4d08dd36.png)

### Any background context you want to provide?

I struggled a bit with what would be the least repetitive and most efficient implementation option, so if you have opinions let me know!

### Relevant tickets

References [Pivotal #173229594](https://www.pivotaltracker.com/story/show/173229594).

### Checklist

- [x] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [x] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

2020-09-11 16:46 UTC, katiecrane commented on resources/assets/helpers/index.js
> +};
Love that you extracted this out into a helper!

2020-09-11 19:48 UTC, katiecrane commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
Was this previously testing the opposite of what it was supposed to?

2020-09-11 19:52 UTC, katiecrane commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +      preview: env('CONTENTFUL_USE_PREVIEW_API'),
Oooo I haven't seen this before! This allows us to test updates to the affiliate in this context before making them live?

2020-09-11 19:53 UTC, katiecrane commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +      preview: env('CONTENTFUL_USE_PREVIEW_API'),
Like on the preview site I guess?

2020-09-11 19:53 UTC, lindsayrmaher commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
i don't think it was testing the opposite per say, but it was failing yesterday on one of Michael's PRs.

2020-09-11 19:57 UTC, lindsayrmaher commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +      preview: env('CONTENTFUL_USE_PREVIEW_API'),
yeah i think it's saying whether we want to be able to preview this particular affiliate?

2020-09-11 20:05 UTC, katiecrane commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +            <PlaceholderText size="large" />
What's this `<PlaceholderText>` component do? I don't think I've run into this one before

2020-09-11 20:07 UTC, katiecrane commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +              the issues that matter to you.
I'm kind of concerned that this copy makes it sounds like you HAVE to register to vote before you're able to complete the quiz and be entered to win the scholarship?

2020-09-11 20:07 UTC, katiecrane commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
Isn't this switching from testing if that test id is showing up vs. is not?

2020-09-11 20:10 UTC, katiecrane commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +              the issues that matter to you.
I know you didn't write this copy though - should I comment on the Pivotal card?

2020-09-11 20:21 UTC, lindsayrmaher commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
yes, but what's tricky is the `sitewide-banner-hidden` testId is added if the banner is hidden, otherwise it is set to `sitewide-banner`. so the length should be 1, even though nothing shows up on the page. if that makes sense.

2020-09-11 20:22 UTC, lindsayrmaher commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +            <PlaceholderText size="large" />
It loads a gray rectangle where the title text should be. It's essentially an alternative to the spinner while the graphql query loads.

2020-09-11 20:22 UTC, lindsayrmaher commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +              the issues that matter to you.
Yeah i think that would be helpful! I agree re: the implications the wording has.

2020-09-11 20:24 UTC, katiecrane commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +            <PlaceholderText size="large" />
That's super cool!!

2020-09-11 20:24 UTC, katiecrane commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
OH got it so this WAS asserting the wrong thing when it had `0` instead of `1`?

2020-09-11 20:35 UTC, lindsayrmaher commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
that's what i'm guessing yah!

2020-09-11 20:43 UTC, katiecrane commented on cypress/integration/sitewide-banner.js
> +    cy.findByTestId('sitewide-banner-hidden').should('have.length', 1);
gotcha!

2020-09-11 20:47 UTC, katiecrane approved these changes
This is good to go once we resolve the question about the copy! Happy to take another look at that point if you'd like or you can feel free to merge

2020-09-14 17:03 UTC, aaronschachter commented on resources/assets/helpers/index.js
> +    if (path.includes('*')) {
Now that this lives in a separate helper (which I agree with @katiecrane is 👍 ), I think this function name seems a little less readable than it could be. It's checking whether the pathname matches one of the patterns in paths -- but it's the other components that call it which use it or the sake of excluding. One day we might want to use it for including something (vs excluding it) based on a path.

What do you think about refactoring to something like `isCurrentPathInPaths(paths)`, and DRY passing the ` window.location.pathname` as an argument?


```suggestion
/**
 * Checks if current path matches an item in given paths array.
 *
 * @param {Array} paths
 * @return {Boolean}
 */
export const isCurrentPathInPaths = (paths) => {
  const pathname = window.location.pathname;
    
  return paths.find(path => {
    if (path.includes('*')) {
```

2020-09-14 17:12 UTC, aaronschachter requested changes

2020-09-14 17:12 UTC, aaronschachter commented on resources/assets/components/blocks/ScholarshipReferralVoterRegistrationBlock/ScholarshipReferralVoterRegistrationBlock.js
> +  query ScholarshipAffiliateQuery($utmLabel: String!, $preview: Boolean!) {
This query name is already used in the [ScholarshipInfoBlock](https://github.com/DoSomething/phoenix-next/blob/d03dbcbb69fea84aa3b91dbba146736729a9c8e9/resources/assets/components/blocks/ScholarshipInfoBlock/ScholarshipInfoBlock.js#L27) -- it needs to be unique to avoid breaking our [schema fetching for cypress tests.](https://dosomething.gitbook.io/phoenix-documentation/installation-+-usage/usage#cypress)

What do you think about creating a new utility component to DRY this GraphQL request and the conditional rendering of the title per `isLoading`,`PlaceholderText` etc?

2020-09-14 17:23 UTC, lindsayrmaher commented on resources/assets/helpers/index.js
> +    if (path.includes('*')) {
agree on the name change! and like the suggestion for setting the pathname var inside the helper

2020-09-14 22:02 UTC, aaronschachter approved these changes
Looking good! Just a few cleanup requests for line breaks that I missed during the first pass. It'd be helpful to see an example URL in the review app to help spot check functionality (or add some tests in a follow up PR...)

2020-09-15 13:47 UTC, merged