update Sitewide banner git page
DoSomething/phoenix-next pull request #2387
Opened 2020-10-09 00:30 UTC by Dinnall

### What's this PR do?

This pull request
Adds a new subtitle for changing the content being displayed on the `SiteWideBanner` 

### How should this be reviewed?

While reading the documentation is there any suggested change that isn't clear? Please flag 

### Any background context you want to provide?
✍️ 📅 

### Relevant tickets

References [Pivotal #175097798](https://www.pivotaltracker.com/story/show/175097798).

### Checklist

- [ x  ] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.

2020-10-13 14:22 UTC, DFurnes approved these changes
Looks great! 📚

2020-10-13 14:22 UTC, DFurnes commented on docs/development/features/sitewide-banner.md
> +-   `/us/quiz-results/*`
I'm wondering if we should link to [this config file](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/components/utilities/SitewideBanner/config.js) instead of duplicating these in documentation. I'm worried that we might forget to update this list later on, and it'd become stale. (Here's, for example, where I took this approach in [Bertly's documentation](https://github.com/DoSomething/bertly/tree/master/documentation#create-link)).

2020-10-14 17:41 UTC, aaronschachter requested changes

2020-10-14 17:41 UTC, aaronschachter commented on docs/development/features/sitewide-banner.md
> +-   `/us/quiz-results/*`
I agree, let's avoid duplicating this list. It'd be ideal to add the permalink to the config in the section above this one, where we document how to configure the excluded paths.

2020-10-14 17:41 UTC, aaronschachter commented on docs/development/features/sitewide-banner.md
> +The content that will be displayed on the banner currently depends on a few variables. We always check if the user is authenticated and voter registration status. If the user has a voter registration
This component has been updated since you added this logic -- we prompt user to verify that they're registered for certain statuses in https://github.com/DoSomething/phoenix-next/pull/2381

2020-10-14 17:43 UTC, aaronschachter commented on docs/development/features/sitewide-banner.md
> +-   `/us/quiz-results/*`
Ah! Realized this change was just to spaces. It would be nice to make the change to the link -- but requesting changes because the logic for displaying the Register To Vote link is out of date.

2020-10-19 16:33 UTC, aaronschachter approved these changes

2020-10-19 16:36 UTC, merged