update a tags on home page
DoSomething/phoenix-next pull request #2475
Opened 2020-12-15 21:48 UTC by Dinnall

### What's this PR do?

This pull request updates the anchor tags on the homepage

### How should this be reviewed?

...

### Any background context you want to provide?

Currennt:
<img width="973" alt="OldScreenShot" src="https://user-images.githubusercontent.com/20409413/102276488-de73b780-3ef4-11eb-93e7-732fc9cefb20.png">

Adjustment:
<img width="1125" alt="NewScreenShot" src="https://user-images.githubusercontent.com/20409413/102276544-f3504b00-3ef4-11eb-823f-d1d7736c90a3.png">

...

### Relevant tickets

References [Pivotal #174220514](https://www.pivotaltracker.com/n/projects/2401401/stories/174220514).

### Checklist

- [ x ] This PR has been added to the relevant Pivotal card.
- [ x ] Added screenshots of front-end changes on small, medium, and large screens.

2020-12-15 22:15 UTC, lindsayrmaher commented on resources/assets/components/pages/HomePage/HomePage.js
> +                    className="font-normal text-blurple-500 hover:text-teal-500 underline"
[the abstract](https://app.abstract.com/projects/fadf0790-f1f9-11e6-9a30-b54ba7e8e705/branches/master/commits/af18709b1da3b70a82b570b181deb27a7360283d/files/565cb50e-dce5-464a-baad-61c33a959c01/layers/DE9622EE-045A-485A-9740-75B323FA104F?mode=design&sha=af18709b1da3b70a82b570b181deb27a7360283d) looks like we just want the underline to be teal rather than the text!

2020-12-16 20:53 UTC, katiecrane commented
hey @Dinnall I'm not sure if [the review app](https://dosomething-phoenix-de-pr-2475.herokuapp.com/us) needs to be rebuilt, but I'm seeing what you have as the "current" state on there and not the "adjustment" state

2020-12-22 16:46 UTC, weerd requested changes

2020-12-22 16:46 UTC, weerd commented on resources/assets/components/pages/HomePage/HomePage.js
> +                    className="font-normal text-blurple-500 hover:text-blurple-300 underline:text-teal-500"
`underline:text-teal-500` this doesn't really do anything... `underline:` isn't a thing.

Did you mean to do `underline hover:text-teal-500`?

2021-01-12 21:37 UTC, weerd approved these changes
👍

2021-01-12 21:39 UTC, merged