Update HomePage.js
DoSomething/phoenix-next pull request #2538
Opened 2021-02-03 20:19 UTC by Dinnall

### What's this PR do?

This pull request adjust the base font color for the anchor tags on the home page 

### How should this be reviewed?

Here is a [Codepen link](https://codepen.io/leah-morgan-angle/pen/rNWVPGm) reference provided by Leah

...

### Any background context you want to provide?

...

### Relevant tickets

References [Pivotal #174220514](https://www.pivotaltracker.com/n/projects/2401401/stories/174220514).

### Checklist

- [ ] This PR has been added to the relevant Pivotal card.

2021-02-03 20:32 UTC, lindsayrmaher commented
It looks like the underline should also update on hover to be teal!

2021-02-04 15:31 UTC, DFurnes commented on resources/assets/components/pages/HomePage/HomePage.js
> +                    className="font-normal underline text-blurple-500 hover:text-blurple-400 text-decoration-color:text-teal-500"
It looks like there isn't a Tailwind utility class (yet), but I think `text-decoration-color` is a great CSS approach!

2021-02-04 15:49 UTC, lindsayrmaher commented on resources/assets/components/pages/HomePage/HomePage.js
> +                    className="font-normal underline text-blurple-500 hover:text-blurple-400 text-decoration-color:text-teal-500"
i think you could use the `text-decoration-color` property within your css definitions vs the `border-bottom`. And we probably want to use the tailwind color classes as well since we now have them synced up with Leah :) You can take a similar approach to the way the `tailwindGray` is defined on line 131, and passed into a css attribute like `${tailwindGray['100']}` on line 244.

2021-02-04 18:53 UTC, lindsayrmaher commented
@Dinnall can you add screenshots of the link with the underline in teal showing?

2021-02-04 19:02 UTC, lindsayrmaher requested changes
Just some tweaks, but this is very close to ready! Can you also add screenshots when you push up the next changes? Super helpful for reviewing vs waiting for the preview app to build.

2021-02-04 19:02 UTC, lindsayrmaher commented on resources/assets/components/pages/HomePage/HomePage.js
> +                        color: ${tailwindTeal['500']};
since this is a repeat of the css on line 264, we could DRY this up by defining it as a variable and passing that in for both of these links! I think you had that in an earlier commit and it was a great idea 💡

2021-02-04 20:32 UTC, lindsayrmaher commented
@Dinnall did you push up changes to your code? I saw you resolved the comments but i'm not seeing a new commit.

2021-02-04 20:35 UTC, Dinnall commented
> @Dinnall did you push up changes to your code? I saw you resolved the comments but i'm not seeing a new commit.

 The changes are building 👍🏾

2021-02-04 20:45 UTC, lindsayrmaher approved these changes
this is looking good to me 👍

2021-02-04 20:45 UTC, lindsayrmaher commented on resources/assets/components/pages/HomePage/HomePage.js
> +      text-decoration: underline;
not sure if we need to define the `text-decoration` here since we already are defining it with the `underline` class

2021-02-04 20:49 UTC, Dinnall commented on resources/assets/components/pages/HomePage/HomePage.js
> +      text-decoration: underline;
Makes sense, I can remove it

2021-02-04 21:22 UTC, DFurnes approved these changes
This turned out great! 🎨

2021-02-04 21:25 UTC, merged